import React from 'react';
import { Layers, Database, Sparkles, GitMerge, Cpu, ShieldCheck, Code2, HeartPulse } from 'lucide-react';

export default function About() {
  return (
    <div>
      <div className="card">
        <div className="card-header">
          <h2 className="card-title">
            <Sparkles color="var(--color-primary)" />
            About CardioGuard AI
          </h2>
          <p className="card-subtitle">
            An End-to-End Machine Learning System for Cardiovascular Disease Stratification
          </p>
        </div>

        <div className="insight-box" style={{ marginBottom: '2rem' }}>
          <div className="insight-title">Project Purpose & Scope</div>
          <p className="insight-text">
            CardioGuard AI demonstrates an enterprise-grade ML pipeline combining modern frontend development (React + Vite), high-performance asynchronous API serving (FastAPI), and advanced ensemble modeling to estimate cardiovascular disease risk.
          </p>
        </div>

        <div className="arch-grid">
          <div className="arch-card">
            <Database size={24} color="var(--color-primary)" style={{ marginBottom: '0.65rem' }} />
            <h3>1. Data Preprocessing & Cleaning</h3>
            <p>
              Trained on 70,000 raw patient records. Filters physiological anomalies (e.g., diastolic &gt; systolic, extreme blood pressures) resulting in 68,640 clean records.
            </p>
          </div>

          <div className="arch-card">
            <Layers size={24} color="var(--color-accent)" style={{ marginBottom: '0.65rem' }} />
            <h3>2. Feature Engineering</h3>
            <p>
              Extracts Mean Arterial Pressure (MAP), Pulse Pressure, blood pressure ratios, non-linear log transformations, and age interaction terms encapsulated within an sklearn Pipeline to prevent data leakage.
            </p>
          </div>

          <div className="arch-card">
            <GitMerge size={24} color="var(--color-teal)" style={{ marginBottom: '0.65rem' }} />
            <h3>3. Stacking Ensemble Meta-Learner</h3>
            <p>
              Combines XGBoost, LightGBM, and Histogram Gradient Boosting as base estimators. A cross-validated Logistic Regression meta-model aggregates probabilities to yield a 0.8048 ROC-AUC.
            </p>
          </div>

          <div className="arch-card">
            <Code2 size={24} color="#f59e0b" style={{ marginBottom: '0.65rem' }} />
            <h3>4. Asynchronous Fast Inference</h3>
            <p>
              FastAPI backend provides sub-50ms inference times with Pydantic type validation, CORS security, auto-generated OpenAPI documentation, and multi-endpoint fallback.
            </p>
          </div>
        </div>
      </div>

      <div className="card">
        <div className="card-header">
          <h2 className="card-title">
            <HeartPulse color="var(--color-danger)" />
            Educational & Academic Notice
          </h2>
          <p className="card-subtitle">
            This application is constructed for academic demonstration and computer engineering coursework. Predictions are generated by statistical machine learning models and must not replace professional medical advice.
          </p>
        </div>
      </div>
    </div>
  );
}
